[build]
  publish = "."
  command = "# no build command"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "16"

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "*"
    Access-Control-Max-Age = "86400"
    Cache-Control = "public, max-age=60"

[[redirects]]
  from = "/api/*"
  to = ":splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}

[[redirects]]
  from = "/api/binance/*"
  to = "https://api1.binance.com/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/upbit/*"
  to = "https://crix-api-endpoint.upbit.com/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/exchange/*"
  to = "https://open.er-api.com/:splat"
  status = 200
  force = true 