[build]
  publish = "."
  command = "# no build command"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "16"

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, OPTIONS"
    Access-Control-Allow-Headers = "Accept, Content-Type"
    Access-Control-Max-Age = "86400"
    Cache-Control = "public, max-age=60"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"
    Content-Security-Policy = "default-src 'self' https:; script-src 'self' 'unsafe-inline' https:; style-src 'self' 'unsafe-inline' https:; img-src 'self' https: data:;"

[[redirects]]
  from = "/api/*"
  to = ":splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}

[[redirects]]
  from = "/api/binance"
  to = "https://api1.binance.com/api/v3/ticker/24hr?symbol=BTCUSDT"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}

[[redirects]]
  from = "/api/exchange"
  to = "https://api.exchangerate-api.com/v4/latest/USD"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}

[[redirects]]
  from = "/api/blockchain"
  to = "https://blockchain.info/q/totalbc"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"} 