[build]
  publish = "."
  command = "# no build command"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "16"

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, OPTIONS"
    Access-Control-Allow-Headers = "Accept, Content-Type"
    Access-Control-Max-Age = "86400"
    Cache-Control = "public, max-age=60"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[redirects]]
  from = "/api/*"
  to = ":splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}

[[redirects]]
  from = "/api/binance"
  to = "https://api1.binance.com/api/v3/ticker/24hr?symbol=BTCUSDT"
  status = 200
  force = true

[[redirects]]
  from = "/api/upbit"
  to = "https://api.upbit.com/v1/ticker?markets=KRW-BTC"
  status = 200
  force = true

[[redirects]]
  from = "/api/blockchain"
  to = "https://blockchain.info/q/totalbc"
  status = 200
  force = true 